If:
    PathMatch: [.*\.cpp, .*\.c, .*\.h, .*\.cxx, .*\.cc, .*\.C]
CompileFlags:                     # Tweak the parse settings
            Add: [
                    -xc++, 
                    -Wall, 
                    -pthread, 
                    -std=c++11, 
                    -m64, 
                    -I./include,
                    -I../include,
                    -I/Users/wutong/workspace/qmk_firmware/include, 
                    -I/Users/wutong/workspace/qmk_firmware/quantum, 
                    -L/Users/wutong/workspace/qmk_firmware/lib,
                  ]
